workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    environment:
      node: latest
      java: 11
      npm: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
